# Generated by Django 2.1.5 on 2019-02-10 22:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the title of the game', max_length=200)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(help_text='Description of the game', max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('players', models.CharField(help_text='Number of players (e.g.2-5)', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoardGameInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular game in the store', primary_key=True, serialize=False)),
                ('condition', models.CharField(blank=True, choices=[('n', 'New'), ('u', 'Used'), ('d', 'Damaged')], default='n', help_text='Book availability', max_length=1)),
                ('board_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BoardGame')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the title of the game', max_length=200)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(help_text='Description of the game', max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('singleplayer', models.BooleanField(default=True)),
                ('multiplayer', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoGameInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular game in the store', primary_key=True, serialize=False)),
                ('condition', models.CharField(blank=True, choices=[('n', 'New'), ('u', 'Used'), ('d', 'Damaged')], default='n', help_text='Book availability', max_length=1)),
                ('missing_case', models.BooleanField(default=False)),
                ('video_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.VideoGame')),
            ],
        ),
        migrations.RemoveField(
            model_name='board_game',
            name='company',
        ),
        migrations.RemoveField(
            model_name='board_game',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Video_Game',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Enter the company that made this game', max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Game genre (e.g. Stratagy, RPG)', max_length=50),
        ),
        migrations.DeleteModel(
            name='Board_Game',
        ),
        migrations.AddField(
            model_name='videogame',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Company'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='genre',
            field=models.ManyToManyField(to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Company'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='genre',
            field=models.ManyToManyField(to='catalog.Genre'),
        ),
    ]
