# Generated by Django 2.1.5 on 2019-02-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190210_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a consolw (e.g. Xbox One, PC, Nintendo 64', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='videogame',
            name='console',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Console'),
        ),
    ]
