# Generated by Django 2.1.5 on 2019-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190213_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='board_game',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='video_game',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(help_text='Enter the title of the game you would like added', max_length=200, null=True),
        ),
    ]
